version: '3'
services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    command: 
      - '--config.file=/etc/prometheus/prometheus.yml'
    network_mode: host

  grafana:
    image: grafana/grafana
    environment:
      - GL_SERVER_ROOT_URL=http://grafana-server
      - GF_SECURITY_ADMIN_USER=voodoone
      - GF_SECURITY_ADMIN_PASSWORD=voodoone
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./provisioning:/etc/grafana/provisioning
      - ./provisioning/dashboards:/var/lib/grafana/dashboards
    network_mode: host

  node-exporter:
    image: prom/node-exporter
    network_mode: host

volumes:
  grafana-storage:
